.gitignore
src/Plugin/Field/FieldWidget/StrawberryFieldWebFormWidget.php
src/Plugin/WebformElement/WebformLoC.php
src/Plugin/WebformElement/WebformWikiData.php
src/Plugin/WebformHandler/strawberryFieldharvester.php
webform_strawberryfield.module

- Better normalization of image container for JSON keys: now using activity stream `as:image`
- Prefix Drupal internalities (like fid, etc) to `dr:`
- Fix missing labels for Authority Record Webform Field autocompletes
Funny: LoC and WikiData endpoint access from AWS wows.
`@TODO:`Make sure we publish a valid `@context` that includes ActivityStream and dr: so not PHP, code, reading apps, if we ever expose our raw internalities, know what is what.

Webform logic updates

---

js/hidenodesubmit-webform_strawberryfield.js
webform_strawberryfield.libraries.yml
webform_strawberryfield.module

This pull makes sure
* that inline webforms used as Widgets for a Strawberry field behave better.
* It also adds an experimental, JS only, hidding/show of the node submit button.  This needs more work to be bullet proof and discussion can happen to move this to a theming layer (or a toggle) instead of directly to a hardcoded decision. 
* It removes the close button since we are moving away (for now) of having a Modal Dialog for the webform as @natehill requested during its UI simplification.

Inline webform work

---

js/hidenodesubmit-webform_strawberryfield.js
webform_strawberryfield.module

I had selectors wrong. Also "hidden" css class breaks in certain themes like Bootstrap 4. This takes care of the context of this JS action in a cleaner way

Fix button hiding JS

---

webform_strawberryfield.module

See #17 
Adds a simple check for the existance of a `#type` key on our webform alter hook. This part of the code just deals with adding diret link buttons to each webform step to allow people to go directly to a certain step and make corrections before Saving metadata, when on the final preview step. When this fails Webform data never gets persisted to the private storage used to keep values around.
This is something new and seems to be triggered by some change in Webform 5.2 >
Pull this branch or apply a patch to your webform strawberryfield.
Ingest a new Object, follow every step, press "Preview" before saving metadata. Once there, press "Save Metadata".  Save the Node. All values should be visible and present.
@giancarlobi just so you know this is being merged into 8.x-1.0-beta1. I …

ISSUE-7: Deal with empty $form elements for Webform Ingest steps

---

src/Plugin/EntityReferenceSelection/ViewsSolrSelection.php
src/Plugin/views/display/EntityReference.php

See #20 
This adds two new plugins, to allow Drupal to use Views driven by SearchAPI as source for entity reference Autocompletes. This way we can filter in a much better and powerful way what entities can be used  in fields like childOf, sceneOf, relatedTo, foaf, etc by having a total fine grained control on filtering Entities by any SBF JSON keys and values indexed in Solr. It also allows our repository to scale way beyond the performance limitations of SQL making autocomplete even possible in realtime on repos with millions of records.
I will follow up with a demo View to be used in an Entity Reference Autocomplete field, and also a Webform setup to use this. The webform will allow, for that element to pass also an extra argument to filter by SBF JSON key "type" which is our equivalent …

ISSUE-20: SearchAPI/Views driven Entity Reference Autocomplete

---

src/Controller/NominatimController.php
webform_strawberryfield.routing.yml

This pull addresses #28 
- Method allows reverse lookup of an address given lat and long
- Add correct call to method in NominatimController->handleRequest
- Create NominatimController::processRequest method to share code between search and reverse
- Add route webform_strawberryfield.nominatim_reverse because of different route params
- Replace broken calls to $this->messenger with static \Drupal::messenger
Call the method. I did this via command line. I also made sure it worked inside `handleRequest`
- `handleRequest` receives a fully formed Request object from a form submit, which then gets used for arguments when it calls `::search`. If you want to test a properly formatted request with `reverse`, here is some code I used (modified from the WebformNominatim #submit callback). Change …

ISSUE-28: Add reverse method to NominatimController.php

---

config/schema/webform_strawberryfield.schema.yml

! This is a work in progress ! addressing #33 
Fixed are:
core.entity_form_display.metadatadisplay_entity.metadatadisplay_entity.default
core.entity_form_display.node.digital_object.super_admin_raw_json
There were several schemas I had problems with.
I will organize them by the errors showing in http://localhost:8001/admin/reports/status
webform.webform.descriptive_metadata
- This is the issue of the harvester spacing ID previously discussed with @DiegoPino 
`id = " strawberryField_webform_handler"`
core.entity_form_display.node.webform.default
- This is commented out in my pull here. `field.widget.settings.webform_entity_reference_autocomplete` with `match_limit` should already be set, but we are getting missing schema for a reason I don't understand

ISSUE-33: Add missing schema

---

src/Plugin/Field/FieldWidget/StrawberryFieldWebFormInlineWidget.php
src/Plugin/Field/FieldWidget/StrawberryFieldWebFormWidget.php

See #37 
This applies to both of our Webform based widgets, inline and click/ajax load ones.
Also, in case of error/json inconsistencies (should never happe but stuff happens) give the user an error message saying what happened (as told by the JSON processor).

ISSUE-37: Enforce Placeholders being used as form element title

---

js/scenebuilder-pannellum_strawberryfield.js
src/Ajax/RemoveHotSpotCommand.php
src/Element/WebformPanoramaTour.php

See #39 
- Issue with Hotspots being re-validated when changing currently being edited Panorama Scene. Changed "select" element for a "radios" one, so i can disable the current Scene when allowing inter-scene hotspots to be added. If not Drupal fails on validating the form because the selected options change and it feels someone is tampering with the form.
- Uses Input and Form State Value setting when adding a new scene. That way currently selected scene (select box) changes also when adding a new scene
- Fixes "Set Current Scene orientation". Need to test this further.
Will keep adding commits to this pull until ready for merging.

ISSUE-39: First pass on better Panorama Tour builder UI

---

js/cameraroll-webform_strawberryfield.js
js/hidenodeaction-webform_strawberryfield.js
src/Element/WebformWithOverride.php
src/EventSubscriber/WebformStrawberryfieldDeleteTmpStorage.php
src/Plugin/Field/FieldWidget/StrawberryFieldWebFormInlineWidget.php
src/Plugin/Field/FieldWidget/StrawberryFieldWebFormWidget.php
webform_strawberryfield.libraries.yml
webform_strawberryfield.module
webform_strawberryfield.services.yml

See #41 
This is a WIP for making the temporary storage for Webform widget/Node interaction better.
This brings a few changes and improvements
- Removes the dystopian and silly idea of hiding/showing via AJAX de node save button on Node State change. That confuses people a lot
- Adds a Temporary Storage deleter Subscriber that triggers when and only when we are sure the Node is save and sleeping in his bed and dreaming with clouds of candy
- Adds a Loader for temporary storage if it was persisted but the node was not saved.This allows broken sessions to be retaken (love this)
- For Object Edits, instead of showing the expanded Webform, it brings back the 'Edit metadata' button. This allows edits to a node, like changing state to happen without having to go into edit mode
TODOS: 
- we …

ISSUE-41a: Make temporary Storage used for Webform persistence stronger

---

composer.json
js/hidenodeaction-webform_strawberryfield.js
src/Controller/StrawberryRunnerModalController.php
src/Plugin/Field/FieldWidget/StrawberryFieldWebFormInlineWidget.php
src/Plugin/Field/FieldWidget/StrawberryFieldWebFormWidget.php
webform_strawberryfield.info.yml
webform_strawberryfield.module

See #26 
Since 26 is a macro issue, this is just a step forward: This pull adds a Cancel Button to any ADO via a Webform Editing session (editing, not creating from 0) which triggers also Edit Buttons from the main Node Form to be displayed again and the original "Edit SOMEPLACEHOLDER TEXT YOU DECIDED ON" to appear back. Logic is simple and most of that is Ajax Commands being send as response to the existing Model Controller we built back in the days: 
Also covers
#56 Drupal 9!
- Modal popup again possible via code. `@TODO:` Expose as an setting to the Widget. So people can decide if they want the inline form (as they get now) or the popup a new one (as they got in 2019)
- EXIF was having trouble to process files with names, etc when that option was enabled on upload. To be honest i don't …

ISSUE-26: Add a Cancel Edit button to Webform widget editing

---

js/hidenodeaction-webform_strawberryfield.js
src/Element/WebformNominatim.php
src/Plugin/Field/FieldWidget/StrawberryFieldWebFormWidget.php

As always this is moving #26 forward.
- Hide Save/Moderation State in every multistep widget (except raw) we provide and make JQuery selects more precise
- Make sure it shows back when needed!
- Attach JS library directly on the normal webform widget (the one that is not inline) just in case form alter/JS does not work via ajax. There is a back and forth in D8/9 core about the issue so better to be safe

Issue 26b: declutter webform ingest

---

composer.json
src/Controller/StrawberryRunnerModalController.php
src/Plugin/Field/FieldWidget/StrawberryFieldWebFormInlineWidget.php
src/Plugin/WebformHandler/strawberryFieldharvester.php

See #85 and #84 
The last one is just clean up of old code we no (hopefully!) need anymore since Event Subscribers are in charge of persisting and classifying. Makes webform operations faster. But I need to test this before merging.

ISSUE-85 and ISSUE-84: Allow multivalued Webform elements to read single valued JSON data

---

src/Element/WebformMultiAgent.php

See #92 
This is a super tiny fix but gets rid of the message. Pretty sure `#title` element key is not a requirement, but it is good to have, even if we are actually hiding it.
@alliomeria

ISSUE-92: adds missing #title  to WebformMultiAgent Agent Type input

---

composer.json
src/Element/WebformPanoramaTour.php

A bug fix. See #95 to read more about my adventures at not thinking straight.
This pull changes incremental ID Hotspot ids to UUID suffixed ones. That way when people delete/add/delete/add the actual sequence does not matter anymore and we have no more Conflicting HTML Ids and Ajax chananigans 🤦 
I also used the occasion to move to RC2, upgrade to webform 5.23 on Drupal 8 (still on 6.0 for 9.1).

Issue 95: make Hotspot Ids really unique and move to RC2 updating Webform Module Version dependency

---

src/Plugin/WebformElement/WebformMetadataDate.php

ISSUE-100 --- fix a bug in \WebformMetadataDate::preSave that caused single value metadata date fields to be saved into json as if they were multi-valued. This resulted in them not being read back into the webform correctly after saving.
See https://github.com/esmero/webform_strawberryfield/commit/04867f1ccaef066c4a5a147946ba487d7213ca56#r47431992

ISSUE-100 - Fix when not $element['#multiple']

---

README.md
config/schema/webform_strawberryfield.schema.yml
js/hidenodeaction-webform_strawberryfield.js
src/Controller/AuthAutocompleteController.php
src/Controller/StrawberryRunnerModalController.php
src/Element/WebformEuropeana.php
src/Element/WebformNominatim.php
src/Plugin/Field/FieldWidget/StrawberryFieldWebFormInlineWidget.php
src/Plugin/Field/FieldWidget/StrawberryFieldWebFormWidget.php
src/Plugin/WebformElement/WebformEuropeana.php

See #122 
Europeana Accepts types: agent, place, concept.
Requires: an api key set inside settings.php. For now Europeana (Alpha 0.5 V) has a single one for everyone but this can change.
IMPROTANT: To test put this:
```PHP
$settings['webform_strawberryfield.europeana_entity_apikey'] = 'apidemo';
```
In your settings.php. If not the controller will not query and a message to the user (somewhere when the user is in the Page and not in the controller url of course)
The `API` is quite unstable and may change in the future so I see this as experimental. Actually the DOCS are not 1:1 with the API response anyways..
Also updates `README.md` and.. wait for it.
Caches queries/responses for a week. This should give some `LoD endpoints` some peace of mind and helps with repeating responses. Caches …

ISSUE-122: Europeana Entity Suggest Webform element and Controller + cache

---

src/Controller/AuthAutocompleteController.php
src/Plugin/Field/FieldWidget/StrawberryFieldWebFormInlineWidget.php
src/Plugin/WebformElement/WebformEuropeana.php
src/Plugin/WebformElement/WebformGetty.php
src/Plugin/WebformElement/WebformLoC.php
src/Plugin/WebformElement/WebformMultiAgent.php
src/Plugin/WebformElement/WebformNominatim.php

See #124 
Each webform element has some inherited base properties, we neglected on inheriting the right ones when overriding the defaults disabling because of the that a Access and also Advanced tab properties used to configured element instances in a webform
This pull should fix the issue and goes into RC3
@giancarlobi you want to update once its merged and @dmer @patdunlavey you want to test and see if all is working afterwards.

ISSUE-124: Inherit right "defineDefaultBaseProperties" for LoD webform elements

---

.gitignore
composer.json
src/Controller/AuthAutocompleteController.php
src/Controller/StrawberryRunnerModalController.php
src/Element/WebformMesh.php
src/Element/WebformSnac.php
src/EventSubscriber/WebformStrawberryfieldDeleteTmpStorage.php
src/Plugin/Field/FieldWidget/StrawberryFieldWebFormInlineWidget.php
src/Plugin/WebformElement/WebformMesh.php
src/Plugin/WebformElement/WebformSnac.php
src/Plugin/WebformHandler/strawberryFieldharvester.php

See #127 and #128
- Adds new webform element for SNAC https://snaccooperative.org
- Deeply reforms Draft Saving. On Object Edit open Drafts are untouched. On cloning (and any Code base Entity Duplication) Drafts are not used so you do not end with legacy data. 
- "you have an unfinished" session message now is part of the Widget Title (to avoid aggressive themes to try to show that as a message on every Form/webform submit (even hidden operations like changing the Type of Agent triggered this on the Bootstrap Barrio theme)

ISSUE-127 and ISSUE-128: adds snac + better draft session management when editing/cloning

---

src/Plugin/WebformElement/WebformMetadataDate.php

Resolves #140 
@DiegoPino Gave this a shot, but not sure I understood all about the issue so glad to make additional changes.

ISSUE-140: WebformMetadataDate wrongly array filters empties

---

src/Element/WebformPanoramaTour.php
src/Plugin/EntityReferenceSelection/ViewsSolrSelection.php
src/Plugin/views/display/EntityReference.php

See #153 
This removes it and allows the actual field/type of field searched for to deal with "contains". There is no "starts" with in Solr/Lucene but an exact match will happen if the field is a non-full-text string.
Also note for @alliomeria we have been doing this a bit wrong! The actual searched fields are part of the Options on the top, the filter we add is basically "useless". It always uses the configured "fields", the "filters" are used as additional to the the autocomplete match. I hate Drupal sometimes!

ISSUE-153: Solr driven entity autocomplete can not use match operator

---

src/Plugin/views/display/EntityReference.php

See #157 
Deprecation notice affecting Views/Solr Entity Reference on newer Search API (I hate deprecations)

ISSUE-157: Fix Autocomplete deprecation (search api 1.24+)

---

src/Plugin/views/display/EntityReference.php

See #159 
Simple house keeping. Nothing exciting, but required for API use of Views + https://github.com/esmero/format_strawberryfield/pull/362

ISSUE-159: Add defaults to Solr Driven autocomplete for when called programmatically

---

src/Controller/AuthAutocompleteController.php

For https://github.com/esmero/ami/issues/185, to complement  https://github.com/esmero/ami/pull/186
Update logic for processing MeSH queries:
- for count > 0 (instead of 1)
- make use of array_unshift to better sort and select results that more closely match original query
Coded live by @DiegoPino and shared with @alliomeria for local testing. Thank you @DiegoPino!

Update for MeSH Autocomplete

---

src/Controller/AuthAutocompleteController.php

See #171 but also #169 
@alliomeria on your radar please

ISSUE-171: levenshtein sorting Input v/s result labels (not description)

---

src/Controller/AuthAutocompleteController.php

See #171 . But I need to remove the additional help (description) from the sorting, or short descriptions for same terms will always win.

ISSUE-171: Sorry, Forgot to remove the 'Desc' from the label when sorting

---

src/Plugin/views/display/EntityReference.php

See #174 
Also don't override any Code/based limits set before by someone

ISSUE-174: adds a fixed "10" rows limit while previewing any Entity Reference Search API (solr) views
